#:schema node_modules/wrangler/config-schema.json
name = "convert"
main = "src/index.js"
compatibility_date = "2025-11-26"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "8943789ed0af49659f887fc740d11240" }
]
