#:schema node_modules/wrangler/config-schema.json
name = 'cccsub'
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "169fec5783b34777bef9b7e17724bb23" }
]

[assets]
directory = "./public"
